### ISSUE TITLE
nvr?

### ISSUE THREAD

**Issue by huyz** [jesse-c/AppearanceNotifier#11]
This shells out and invokes `nvr`.  But what is it?   No mention of it anywhere

**Comment by huyz** [comment]
Ah I finally found it: https://github.com/mhinz/neovim-remote

But what if we're only using Kitty and not neovim?  Shouldn't be relevant to me in that case.

**Comment by jesse-c** [comment]
It is mentioned in the README, though not by the binary name of `nvr`.

The current applications that are controlled aren't configurable at the moment, along with the themes.

You'd have to modify the source code [1] to even have it set the right Kitty themes.

I have _thought_ about making it all configurable.

[1] https://github.com/jesse-c/AppearanceNotifier/blob/main/Sources/AppearanceNotifier/main.swift#L102

**Comment by jesse-c** [comment]
Added the alias to the README
