### ISSUE TITLE
Readme on how to use with helix

### ISSUE THREAD

**Issue by forivall** [jesse-c/AppearanceNotifier#13]
It would be great to have some info on how to set up helix to use with this! (Found via your comment [here](https://github.com/helix-editor/helix/pull/7541#issuecomment-1635694446))

**Comment by jesse-c** [comment]
If you don't mind using the Catppuccin theme [1] (specifically, th Mocha and Latte variants), then you can change your Helix config to be like my config [2]. If you'd like to use your own themes, you'd need to edit the source code!

[1] https://github.com/catppuccin/helix
[2] https://github.com/jesse-c/dotfiles/blob/main/home/dot_config/helix/config.toml#L1

**Comment by jesse-c** [comment]
Updated the README [1]. :)

[1] https://github.com/jesse-c/AppearanceNotifier/commits/main/

**Comment by forivall** [comment]
Thanks so much! Yeah, this will be enough to get me going.

(_(long parenthetical)_ though i'll re-visit it when i properly set up the helix theme to my liking. I'll need to port over my modestly customized vscode versions of base16/tomorrow themes (which i've recently coined as [tuesday (light) and thursday (dark)](https://github.com/forivall/dotfiles/tree/osx/vscode/theme)))

So far, with my light use of helix, i've just used base16_transparent. I use iterm with a [light/dark AutoLaunch python script
](https://github.com/forivall/dotfiles/blob/osx/iterm2/Scripts/AutoLaunch/switch_automatic.py), so with the transparent theme, it just uses the terminal colors already, the colors switch, but i'm missing a couple extra customizations.

**Comment by jesse-c** [comment]
I agree re: Catppuccin being a little too blue. Those 2 variants I use I find to be the most _bearable_. I at the moment wouldn't dare attempt to customse it or make a new theme, since there's themes for almost every app, for Catppuccin. 😅 

I had no idea that iTerm had the kind of functionality, so it's interesting to see.
